### ISSUE TITLE
qprocess_os2.cpp

### ISSUE THREAD

**Issue by lerdmann** [psmedley/qt6-base-os2#10]
https://github.com/psmedley/qt6-base-os2/blob/befd6908f1036f39001beadfb403d851b614b0e8/src/corelib/io/qprocess_p.h#L272

instead of #else, bracket with #ifdef Q_OS_WIN (union to follow is only for Windows)

**Comment by psmedley** [comment]
Thanks - I've fixed this locally, but github isn't letting me commit the change right now.
