### ISSUE TITLE
File picker in Dooble does not show some directories

### ISSUE THREAD

**Issue by dryeo** [psmedley/qt6-base-os2#9]
Using a file dialog in Dooble, to lets say import the block list, fails to display the directory listing on the drive that it is running from. Home is on the same drive as well, haven't tested which breaks it yet.

**Comment by dryeo** [comment]
Further testing shows it is the drive it is installed to, currently L:\qt6 here.

**Comment by psmedley** [comment]
I've seen some similar behavior in other apps, so I'm confident this is in qtbase.

There are some clues in tst_qstorageinfo that path handling still isn't quite right...

FAIL!  : tst_QStorageInfo::root() Compared values are not the same
   Actual   (storage.rootPath()): "/"
   Expected (QDir::rootPath())  : "C:/"
   Loc: [../tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo.cpp(135)]

**Comment by psmedley** [comment]
OK - part of this is that in Qt5 we were using qstorageinfo_stubs.cpp (https://github.com/bitwiseworks/qtbase-os2/blob/master/src/corelib/io/io.pri#L217)

This file doesn't exist in Qt6,  so I chose to use qstorageinfo_unix.cpp - this will need some work :)

**Comment by psmedley** [comment]
https://smedley.id.au/tmp/qt6-6.2.4-qt6gui-20230127.zip appears to correct this behvaiour
